---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  variable_files:
    - test/fixtures/tf_module/temp.tfvars

provisioner:
  name: terraform

verifier:
  name: shell
  command: inspec exec test/integration/my-profile -t gcp:// --attrs test/integration/my-profile/attributes.yml

suites:
  - name: my-profile

platforms:
  - name: terraform